### ISSUE TITLE
Trynig to install your package with scriptcs, failing with need of newer NuGet client.

### ISSUE THREAD

**Issue by dealproc** [azure-contrib/scriptcs-azuremanagement#5]
```
C:\>scriptcs -install ScriptCs.AzureManagement -pre
INFO: Installing packages...
ERROR: Installation failed: ScriptCs.AzureManagement
ERROR: The 'Microsoft.Bcl 1.1.9' package requires NuGet client version '2.8.1' or above, but the current NuGet version is '2.7.40808.167'.
INFO: Installation completed successfully.
INFO: Saving packages in packages.config...
INFO: Packages directory does not exist!
```

Any assistance anyone can offer?

**Comment by paulbouwer** [comment]
This is related to scriptcs [issue #688](https://github.com/scriptcs/scriptcs/issues/688). This will be resolved in v0.10.0 of scriptcs, which is being released soon.

If you cannot wait until v0.10.0 is released, you can also install v0.10.0 from the nightlies. It is in the final stages of being prepped for release so is stable.

You can install the nightly version via chocolatey as follows:

`cinst scriptcs -pre -source https://www.myget.org/F/scriptcsnightly/`

**Comment by dealproc** [comment]
Where does the nightly get installed?  I did that already, but the path is still pointing to v0.9.0.

**Comment by dealproc** [comment]
got it... had to uninstall 0.9.0 to get it up and running... awesome... thx. dude.

**Comment by paulbouwer** [comment]
@dealproc Glad you got it sorted out. I'm currently working on **scriptcs version manager** - [svm](https://github.com/paulbouwer/svm) to make managing multiple versions much better.

**Comment by dealproc** [comment]
yea... trying to automate configuring Azure... i'm not a powershell dev, and thought scriptcs with your stuff would be better... alas, my C#-fu isn't as strong outside of VS.NET as it is inside of VS.NET.

I may need to develop it as a c# class, then copy and paste it into a *.csx and run it... not sure yet.

Any suggestions?

Sublime Text 2, although has autocomplete support, doesn't seem to be reflecting and displaying the properties of the custom classes... only the main .net fx stuff.

**Comment by paulbouwer** [comment]
The Script Pack probably needs to take the next step and make interacting with the underlying MAML apis easier :)
